spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudnote?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root

mybatis:
    type-aliases-package: cn.edu.bigc.cloudnote.model
    mapper-locations: classpath:mapper/*.xml

server:
    port: 8081
